# uhm parent-shell integration v1 (Fish). Generated by `uhm shell-init fish`.
function uhm
    set -l __uhm_previous $status
    set -l __uhm_binary (command -s uhm | head -n 1)
    if test -z "$__uhm_binary"; or not test -x "$__uhm_binary"
        printf '%s\n' 'uhm: executable not found on PATH' >&2
        return 15
    end
    set -l __uhm_history_args
    if "$__uhm_binary" shell-history-enabled >/dev/null 2>&1
        set -l __uhm_history (history --max=1 2>/dev/null | string collect)
        if test -n "$__uhm_history"
            set __uhm_history_args --uhm-last-history "$__uhm_history"
        end
    end
    set -l __uhm_open ("$__uhm_binary" --uhm-shell fish --uhm-parent-cwd "$PWD" --uhm-parent-status "$__uhm_previous" shell-control-open)
    or return 15
    set -l __uhm_parts (string split \t -- "$__uhm_open")
    if test (count $__uhm_parts) -ne 2
        printf '%s\n' 'uhm: shell integration could not open its private control directory' >&2
        return 15
    end
    set -l __uhm_dir $__uhm_parts[1]
    set -l __uhm_nonce $__uhm_parts[2]
    "$__uhm_binary" --uhm-control-dir "$__uhm_dir" --uhm-control-nonce "$__uhm_nonce" $__uhm_history_args $argv
    set -l __uhm_child $status
    set -l __uhm_final $__uhm_child
    if test $__uhm_child -eq 0; and begin; test -e "$__uhm_dir/response.json"; or test -L "$__uhm_dir/response.json"; end
        set -l __uhm_lines ("$__uhm_binary" --uhm-shell fish --uhm-control-dir "$__uhm_dir" --uhm-control-nonce "$__uhm_nonce" shell-validate)
        if test $status -ne 0
            printf '%s\n' 'uhm: parent action was not applied; inspect the proposal and retry after reinstalling shell integration' >&2
            set __uhm_final 15
        else
            eval (string join \n -- $__uhm_lines)
            set -l __uhm_apply $status
            set -l __uhm_ack applied
            if test $__uhm_apply -ne 0
                set __uhm_ack failed
                set __uhm_final 15
                printf '%s\n' 'uhm: parent action returned failure; inspect your current shell state before retrying' >&2
            end
            "$__uhm_binary" --uhm-control-dir "$__uhm_dir" --uhm-control-nonce "$__uhm_nonce" shell-ack "$__uhm_ack" >/dev/null; or true
        end
    end
    "$__uhm_binary" --uhm-control-dir "$__uhm_dir" --uhm-control-nonce "$__uhm_nonce" shell-clean >/dev/null 2>&1; or true
    return $__uhm_final
end
