# uhm parent-shell integration v1 (Zsh). Generated by `uhm shell-init zsh`.
uhm() {
  local __uhm_previous=$? __uhm_binary __uhm_open __uhm_dir __uhm_nonce __uhm_child __uhm_code __uhm_apply __uhm_final __uhm_ack __uhm_history
  __uhm_binary="$(whence -p uhm)"
  if [[ -z "$__uhm_binary" || ! -x "$__uhm_binary" ]]; then print -u2 -- 'uhm: executable not found on PATH'; return 15; fi
  local -a __uhm_history_args=()
  if "$__uhm_binary" shell-history-enabled >/dev/null 2>&1; then
    __uhm_history="$(builtin fc -ln -2 -2 2>/dev/null)"
    [[ -n "$__uhm_history" ]] && __uhm_history_args=(--uhm-last-history "$__uhm_history")
  fi
  __uhm_open="$("$__uhm_binary" --uhm-shell zsh --uhm-parent-cwd "$PWD" --uhm-parent-status "$__uhm_previous" shell-control-open)" || return 15
  IFS=$'\t' read -r __uhm_dir __uhm_nonce <<< "$__uhm_open"
  if [[ -z "$__uhm_dir" || -z "$__uhm_nonce" ]]; then
    print -u2 -- 'uhm: shell integration could not open its private control directory'
    return 15
  fi
  "$__uhm_binary" --uhm-control-dir "$__uhm_dir" --uhm-control-nonce "$__uhm_nonce" "${__uhm_history_args[@]}" "$@"
  __uhm_child=$?
  __uhm_final=$__uhm_child
  if [[ $__uhm_child -eq 0 && ( -e "$__uhm_dir/response.json" || -L "$__uhm_dir/response.json" ) ]]; then
    __uhm_code="$("$__uhm_binary" --uhm-shell zsh --uhm-control-dir "$__uhm_dir" --uhm-control-nonce "$__uhm_nonce" shell-validate)"
    if [[ $? -ne 0 ]]; then
      print -u2 -- 'uhm: parent action was not applied; inspect the proposal and retry after reinstalling shell integration'
      __uhm_final=15
    else
      eval "$__uhm_code"
      __uhm_apply=$?
      if [[ $__uhm_apply -eq 0 ]]; then __uhm_ack=applied; else __uhm_ack=failed; __uhm_final=15; fi
      "$__uhm_binary" --uhm-control-dir "$__uhm_dir" --uhm-control-nonce "$__uhm_nonce" shell-ack "$__uhm_ack" >/dev/null || true
      if [[ $__uhm_apply -ne 0 ]]; then
        print -u2 -- 'uhm: parent action returned failure; inspect your current shell state before retrying'
      fi
    fi
  fi
  "$__uhm_binary" --uhm-control-dir "$__uhm_dir" --uhm-control-nonce "$__uhm_nonce" shell-clean >/dev/null 2>&1 || true
  return "$__uhm_final"
}
